### ISSUE TITLE
creating talk page using rmd instead of md

### ISSUE THREAD

**Issue by jananiravi** [sourcethemes/project-kickstart-r#3]
The following yaml works perfectly well while listing all talks and the talk page using the slug, but doesn't appear on the home page under #talks widget:

```
---
title: R-Ladies East Lansing | Workshop on Intro to Tidy Data w/ R
author: Janani Ravi
date: '2018-11-05'
slug: rlel-workshop-tidydata
categories:
  - R-Ladies
  - Resources
tags:
  - R
  - rladies
  - datascience
  - software-tools
image:
  caption: ''
  focal_point: ''
selected: true
time_start: 2018-11-05T18:00:00
time_end: 2018-11-05T20:00:00
abstract: ""
abstract_short: ""
event: "R-Ladies East Lansing | November 5, 2018"
event_url: "https://rladies-eastlansing.github.io"
location: "East Lansing, MI"
---
```

Am I missing something here, @gcushen 
Also, to include images inline, should I create a separate folder using the format `X/index.rmd` I understand this works for featured images. How about inserting other images inline for talks/posts? Inserting images from /static/img doesn't seem to be working. thanks!
